---
- name: Install core packages for virtual machines
  hosts: "{{ my_hosts | d('all') }}"
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - prometheus-node-exporter
          - nfs-common
          - qemu-guest-agent
          - unzip
        update_cache: true

    - name: Start guest qemu-guest-agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true
