---
- name: Update all Ubuntu servers
  hosts: "{{ my_hosts | d('all') }}"
  become: true
  tasks:
    - name: System updating
      ansible.builtin.apt:
        upgrade: 'yes'
        update_cache: true

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_files

    - name: Show debug info about reboot the server (if required).
      ansible.builtin.debug:
        msg: "Reboot required"
      when: reboot_required_files.stat.exists
        
    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_files.stat.exists
    
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
