- name: Update all servers
  hosts: "*"
  gather_facts: true
  become: true
  tasks:
    - name: Perform dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_files

    - name: Show debug info about reboot the server (if required).
      ansible.builtin.debug:
        msg: "Reboot required"
      when: reboot_required_files.stat.exists
        
    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_files.stat.exists
    
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
        